-- Vesta e-commerce schema
-- Safe to run alongside the legacy Aurora Chat tables; all shop objects use store_* names.

create table if not exists public.store_products (
  id bigint generated by default as identity primary key,
  sku text unique not null,
  name text not null,
  category text not null,
  description text not null default '',
  price numeric(14,0) not null check (price >= 0),
  compare_at_price numeric(14,0) check (compare_at_price is null or compare_at_price >= price),
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.store_addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  recipient text not null,
  phone text not null,
  province text not null,
  city text not null,
  address text not null,
  postal_code text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.store_wishlists (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.store_products(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

create table if not exists public.store_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  address_id uuid not null references public.store_addresses(id) on delete restrict,
  status text not null default 'pending' check (status in ('pending','paid','processing','shipped','delivered','cancelled')),
  subtotal numeric(14,0) not null default 0,
  shipping_fee numeric(14,0) not null default 0,
  total numeric(14,0) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.store_order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.store_orders(id) on delete cascade,
  product_id bigint references public.store_products(id) on delete set null,
  product_name text not null,
  unit_price numeric(14,0) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now()
);

alter table public.store_products enable row level security;
alter table public.store_addresses enable row level security;
alter table public.store_wishlists enable row level security;
alter table public.store_orders enable row level security;
alter table public.store_order_items enable row level security;

drop policy if exists "store products are readable" on public.store_products;
create policy "store products are readable" on public.store_products
  for select to anon, authenticated using (is_active = true);

drop policy if exists "customers manage their addresses" on public.store_addresses;
create policy "customers manage their addresses" on public.store_addresses
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "customers manage their wishlist" on public.store_wishlists;
create policy "customers manage their wishlist" on public.store_wishlists
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "customers read their orders" on public.store_orders;
create policy "customers read their orders" on public.store_orders
  for select to authenticated using (user_id = auth.uid());

drop policy if exists "customers read their order items" on public.store_order_items;
create policy "customers read their order items" on public.store_order_items
  for select to authenticated using (
    exists (select 1 from public.store_orders o where o.id = order_id and o.user_id = auth.uid())
  );

-- Create orders through this RPC so prices are read from the database, not trusted from the browser.
create or replace function public.place_store_order(p_address_id uuid, p_items jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid;
  v_expected_count integer;
  v_inserted_count integer;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Order must contain at least one item';
  end if;
  if not exists (
    select 1 from public.store_addresses a
    where a.id = p_address_id and a.user_id = v_user_id
  ) then
    raise exception 'Address not found';
  end if;

  v_expected_count := jsonb_array_length(p_items);
  insert into public.store_orders(user_id, address_id)
  values (v_user_id, p_address_id)
  returning id into v_order_id;

  insert into public.store_order_items(order_id, product_id, product_name, unit_price, quantity)
  select v_order_id, p.id, p.name, p.price, (i.item->>'quantity')::integer
  from jsonb_array_elements(p_items) as i(item)
  join public.store_products p on p.id = (i.item->>'product_id')::bigint
  where p.is_active = true
    and (i.item->>'quantity') ~ '^[1-9][0-9]*$';

  get diagnostics v_inserted_count = row_count;
  if v_inserted_count <> v_expected_count then
    raise exception 'One or more products are unavailable or quantities are invalid';
  end if;

  update public.store_orders o
  set subtotal = x.amount,
      total = x.amount + o.shipping_fee
  from (
    select sum(unit_price * quantity) as amount
    from public.store_order_items where order_id = v_order_id
  ) x
  where o.id = v_order_id;

  return v_order_id;
end;
$$;

revoke all on function public.place_store_order(uuid, jsonb) from public;
grant execute on function public.place_store_order(uuid, jsonb) to authenticated;

grant select on public.store_products to anon, authenticated;
grant select, insert, update, delete on public.store_addresses, public.store_wishlists to authenticated;
grant select on public.store_orders, public.store_order_items to authenticated;

create index if not exists store_orders_user_created_idx on public.store_orders(user_id, created_at desc);
create index if not exists store_order_items_order_idx on public.store_order_items(order_id);
